version: '3.8'

services:
  video-channel-web:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - video

networks:
  video:
    name: video
    external: true
